package walker.application.coordinator.entity;

public class WalkerNotify {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column walker_notify.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column walker_notify.gmt_create
     *
     * @mbggenerated
     */
    private Integer gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column walker_notify.gmt_modified
     *
     * @mbggenerated
     */
    private Integer gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column walker_notify.app_id
     *
     * @mbggenerated
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column walker_notify.master_gid
     *
     * @mbggenerated
     */
    private String masterGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column walker_notify.branch_gid
     *
     * @mbggenerated
     */
    private String branchGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column walker_notify.notify_type
     *
     * @mbggenerated
     */
    private Integer notifyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column walker_notify.notify_url
     *
     * @mbggenerated
     */
    private String notifyUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column walker_notify.notify_body
     *
     * @mbggenerated
     */
    private String notifyBody;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column walker_notify.notify_status
     *
     * @mbggenerated
     */
    private Integer notifyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column walker_notify.retry_num
     *
     * @mbggenerated
     */
    private Integer retryNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column walker_notify.is_deleted
     *
     * @mbggenerated
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column walker_notify.id
     *
     * @return the value of walker_notify.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column walker_notify.id
     *
     * @param id the value for walker_notify.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column walker_notify.gmt_create
     *
     * @return the value of walker_notify.gmt_create
     *
     * @mbggenerated
     */
    public Integer getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column walker_notify.gmt_create
     *
     * @param gmtCreate the value for walker_notify.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Integer gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column walker_notify.gmt_modified
     *
     * @return the value of walker_notify.gmt_modified
     *
     * @mbggenerated
     */
    public Integer getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column walker_notify.gmt_modified
     *
     * @param gmtModified the value for walker_notify.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Integer gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column walker_notify.app_id
     *
     * @return the value of walker_notify.app_id
     *
     * @mbggenerated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column walker_notify.app_id
     *
     * @param appId the value for walker_notify.app_id
     *
     * @mbggenerated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column walker_notify.master_gid
     *
     * @return the value of walker_notify.master_gid
     *
     * @mbggenerated
     */
    public String getMasterGid() {
        return masterGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column walker_notify.master_gid
     *
     * @param masterGid the value for walker_notify.master_gid
     *
     * @mbggenerated
     */
    public void setMasterGid(String masterGid) {
        this.masterGid = masterGid == null ? null : masterGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column walker_notify.branch_gid
     *
     * @return the value of walker_notify.branch_gid
     *
     * @mbggenerated
     */
    public String getBranchGid() {
        return branchGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column walker_notify.branch_gid
     *
     * @param branchGid the value for walker_notify.branch_gid
     *
     * @mbggenerated
     */
    public void setBranchGid(String branchGid) {
        this.branchGid = branchGid == null ? null : branchGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column walker_notify.notify_type
     *
     * @return the value of walker_notify.notify_type
     *
     * @mbggenerated
     */
    public Integer getNotifyType() {
        return notifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column walker_notify.notify_type
     *
     * @param notifyType the value for walker_notify.notify_type
     *
     * @mbggenerated
     */
    public void setNotifyType(Integer notifyType) {
        this.notifyType = notifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column walker_notify.notify_url
     *
     * @return the value of walker_notify.notify_url
     *
     * @mbggenerated
     */
    public String getNotifyUrl() {
        return notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column walker_notify.notify_url
     *
     * @param notifyUrl the value for walker_notify.notify_url
     *
     * @mbggenerated
     */
    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl == null ? null : notifyUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column walker_notify.notify_body
     *
     * @return the value of walker_notify.notify_body
     *
     * @mbggenerated
     */
    public String getNotifyBody() {
        return notifyBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column walker_notify.notify_body
     *
     * @param notifyBody the value for walker_notify.notify_body
     *
     * @mbggenerated
     */
    public void setNotifyBody(String notifyBody) {
        this.notifyBody = notifyBody == null ? null : notifyBody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column walker_notify.notify_status
     *
     * @return the value of walker_notify.notify_status
     *
     * @mbggenerated
     */
    public Integer getNotifyStatus() {
        return notifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column walker_notify.notify_status
     *
     * @param notifyStatus the value for walker_notify.notify_status
     *
     * @mbggenerated
     */
    public void setNotifyStatus(Integer notifyStatus) {
        this.notifyStatus = notifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column walker_notify.retry_num
     *
     * @return the value of walker_notify.retry_num
     *
     * @mbggenerated
     */
    public Integer getRetryNum() {
        return retryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column walker_notify.retry_num
     *
     * @param retryNum the value for walker_notify.retry_num
     *
     * @mbggenerated
     */
    public void setRetryNum(Integer retryNum) {
        this.retryNum = retryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column walker_notify.is_deleted
     *
     * @return the value of walker_notify.is_deleted
     *
     * @mbggenerated
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column walker_notify.is_deleted
     *
     * @param isDeleted the value for walker_notify.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}