package walker.application.notify.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import walker.application.notify.entity.WalkerNotify;
import walker.application.notify.entity.WalkerNotifyExample;

public interface WalkerNotifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walker_notify
     *
     * @mbggenerated
     */
    int countByExample(WalkerNotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walker_notify
     *
     * @mbggenerated
     */
    int deleteByExample(WalkerNotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walker_notify
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walker_notify
     *
     * @mbggenerated
     */
    int insert(WalkerNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walker_notify
     *
     * @mbggenerated
     */
    int insertSelective(WalkerNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walker_notify
     *
     * @mbggenerated
     */
    List<WalkerNotify> selectByExample(WalkerNotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walker_notify
     *
     * @mbggenerated
     */
    WalkerNotify selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walker_notify
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WalkerNotify record, @Param("example") WalkerNotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walker_notify
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WalkerNotify record, @Param("example") WalkerNotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walker_notify
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WalkerNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walker_notify
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WalkerNotify record);
}