package walker.application.notify.entity;

import java.util.ArrayList;
import java.util.List;

public class WalkerTransactionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table walker_transaction
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table walker_transaction
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table walker_transaction
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walker_transaction
     *
     * @mbggenerated
     */
    public WalkerTransactionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walker_transaction
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walker_transaction
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walker_transaction
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walker_transaction
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walker_transaction
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walker_transaction
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walker_transaction
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walker_transaction
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walker_transaction
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walker_transaction
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table walker_transaction
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Long value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Long value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Long value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Long value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Long value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Long value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Long> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Long> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Long value1, Long value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Long value1, Long value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Long value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Long value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Long value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Long value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Long value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Long value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Long> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Long> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Long value1, Long value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Long value1, Long value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNull() {
            addCriterion("app_id is null");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNotNull() {
            addCriterion("app_id is not null");
            return (Criteria) this;
        }

        public Criteria andAppIdEqualTo(String value) {
            addCriterion("app_id =", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotEqualTo(String value) {
            addCriterion("app_id <>", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThan(String value) {
            addCriterion("app_id >", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThanOrEqualTo(String value) {
            addCriterion("app_id >=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThan(String value) {
            addCriterion("app_id <", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThanOrEqualTo(String value) {
            addCriterion("app_id <=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLike(String value) {
            addCriterion("app_id like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotLike(String value) {
            addCriterion("app_id not like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdIn(List<String> values) {
            addCriterion("app_id in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotIn(List<String> values) {
            addCriterion("app_id not in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdBetween(String value1, String value2) {
            addCriterion("app_id between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotBetween(String value1, String value2) {
            addCriterion("app_id not between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andMasterGidIsNull() {
            addCriterion("master_gid is null");
            return (Criteria) this;
        }

        public Criteria andMasterGidIsNotNull() {
            addCriterion("master_gid is not null");
            return (Criteria) this;
        }

        public Criteria andMasterGidEqualTo(String value) {
            addCriterion("master_gid =", value, "masterGid");
            return (Criteria) this;
        }

        public Criteria andMasterGidNotEqualTo(String value) {
            addCriterion("master_gid <>", value, "masterGid");
            return (Criteria) this;
        }

        public Criteria andMasterGidGreaterThan(String value) {
            addCriterion("master_gid >", value, "masterGid");
            return (Criteria) this;
        }

        public Criteria andMasterGidGreaterThanOrEqualTo(String value) {
            addCriterion("master_gid >=", value, "masterGid");
            return (Criteria) this;
        }

        public Criteria andMasterGidLessThan(String value) {
            addCriterion("master_gid <", value, "masterGid");
            return (Criteria) this;
        }

        public Criteria andMasterGidLessThanOrEqualTo(String value) {
            addCriterion("master_gid <=", value, "masterGid");
            return (Criteria) this;
        }

        public Criteria andMasterGidLike(String value) {
            addCriterion("master_gid like", value, "masterGid");
            return (Criteria) this;
        }

        public Criteria andMasterGidNotLike(String value) {
            addCriterion("master_gid not like", value, "masterGid");
            return (Criteria) this;
        }

        public Criteria andMasterGidIn(List<String> values) {
            addCriterion("master_gid in", values, "masterGid");
            return (Criteria) this;
        }

        public Criteria andMasterGidNotIn(List<String> values) {
            addCriterion("master_gid not in", values, "masterGid");
            return (Criteria) this;
        }

        public Criteria andMasterGidBetween(String value1, String value2) {
            addCriterion("master_gid between", value1, value2, "masterGid");
            return (Criteria) this;
        }

        public Criteria andMasterGidNotBetween(String value1, String value2) {
            addCriterion("master_gid not between", value1, value2, "masterGid");
            return (Criteria) this;
        }

        public Criteria andBranchGidIsNull() {
            addCriterion("branch_gid is null");
            return (Criteria) this;
        }

        public Criteria andBranchGidIsNotNull() {
            addCriterion("branch_gid is not null");
            return (Criteria) this;
        }

        public Criteria andBranchGidEqualTo(String value) {
            addCriterion("branch_gid =", value, "branchGid");
            return (Criteria) this;
        }

        public Criteria andBranchGidNotEqualTo(String value) {
            addCriterion("branch_gid <>", value, "branchGid");
            return (Criteria) this;
        }

        public Criteria andBranchGidGreaterThan(String value) {
            addCriterion("branch_gid >", value, "branchGid");
            return (Criteria) this;
        }

        public Criteria andBranchGidGreaterThanOrEqualTo(String value) {
            addCriterion("branch_gid >=", value, "branchGid");
            return (Criteria) this;
        }

        public Criteria andBranchGidLessThan(String value) {
            addCriterion("branch_gid <", value, "branchGid");
            return (Criteria) this;
        }

        public Criteria andBranchGidLessThanOrEqualTo(String value) {
            addCriterion("branch_gid <=", value, "branchGid");
            return (Criteria) this;
        }

        public Criteria andBranchGidLike(String value) {
            addCriterion("branch_gid like", value, "branchGid");
            return (Criteria) this;
        }

        public Criteria andBranchGidNotLike(String value) {
            addCriterion("branch_gid not like", value, "branchGid");
            return (Criteria) this;
        }

        public Criteria andBranchGidIn(List<String> values) {
            addCriterion("branch_gid in", values, "branchGid");
            return (Criteria) this;
        }

        public Criteria andBranchGidNotIn(List<String> values) {
            addCriterion("branch_gid not in", values, "branchGid");
            return (Criteria) this;
        }

        public Criteria andBranchGidBetween(String value1, String value2) {
            addCriterion("branch_gid between", value1, value2, "branchGid");
            return (Criteria) this;
        }

        public Criteria andBranchGidNotBetween(String value1, String value2) {
            addCriterion("branch_gid not between", value1, value2, "branchGid");
            return (Criteria) this;
        }

        public Criteria andIsDeclareIsNull() {
            addCriterion("is_declare is null");
            return (Criteria) this;
        }

        public Criteria andIsDeclareIsNotNull() {
            addCriterion("is_declare is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeclareEqualTo(Boolean value) {
            addCriterion("is_declare =", value, "isDeclare");
            return (Criteria) this;
        }

        public Criteria andIsDeclareNotEqualTo(Boolean value) {
            addCriterion("is_declare <>", value, "isDeclare");
            return (Criteria) this;
        }

        public Criteria andIsDeclareGreaterThan(Boolean value) {
            addCriterion("is_declare >", value, "isDeclare");
            return (Criteria) this;
        }

        public Criteria andIsDeclareGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_declare >=", value, "isDeclare");
            return (Criteria) this;
        }

        public Criteria andIsDeclareLessThan(Boolean value) {
            addCriterion("is_declare <", value, "isDeclare");
            return (Criteria) this;
        }

        public Criteria andIsDeclareLessThanOrEqualTo(Boolean value) {
            addCriterion("is_declare <=", value, "isDeclare");
            return (Criteria) this;
        }

        public Criteria andIsDeclareIn(List<Boolean> values) {
            addCriterion("is_declare in", values, "isDeclare");
            return (Criteria) this;
        }

        public Criteria andIsDeclareNotIn(List<Boolean> values) {
            addCriterion("is_declare not in", values, "isDeclare");
            return (Criteria) this;
        }

        public Criteria andIsDeclareBetween(Boolean value1, Boolean value2) {
            addCriterion("is_declare between", value1, value2, "isDeclare");
            return (Criteria) this;
        }

        public Criteria andIsDeclareNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_declare not between", value1, value2, "isDeclare");
            return (Criteria) this;
        }

        public Criteria andTxStatusIsNull() {
            addCriterion("tx_status is null");
            return (Criteria) this;
        }

        public Criteria andTxStatusIsNotNull() {
            addCriterion("tx_status is not null");
            return (Criteria) this;
        }

        public Criteria andTxStatusEqualTo(Integer value) {
            addCriterion("tx_status =", value, "txStatus");
            return (Criteria) this;
        }

        public Criteria andTxStatusNotEqualTo(Integer value) {
            addCriterion("tx_status <>", value, "txStatus");
            return (Criteria) this;
        }

        public Criteria andTxStatusGreaterThan(Integer value) {
            addCriterion("tx_status >", value, "txStatus");
            return (Criteria) this;
        }

        public Criteria andTxStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("tx_status >=", value, "txStatus");
            return (Criteria) this;
        }

        public Criteria andTxStatusLessThan(Integer value) {
            addCriterion("tx_status <", value, "txStatus");
            return (Criteria) this;
        }

        public Criteria andTxStatusLessThanOrEqualTo(Integer value) {
            addCriterion("tx_status <=", value, "txStatus");
            return (Criteria) this;
        }

        public Criteria andTxStatusIn(List<Integer> values) {
            addCriterion("tx_status in", values, "txStatus");
            return (Criteria) this;
        }

        public Criteria andTxStatusNotIn(List<Integer> values) {
            addCriterion("tx_status not in", values, "txStatus");
            return (Criteria) this;
        }

        public Criteria andTxStatusBetween(Integer value1, Integer value2) {
            addCriterion("tx_status between", value1, value2, "txStatus");
            return (Criteria) this;
        }

        public Criteria andTxStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("tx_status not between", value1, value2, "txStatus");
            return (Criteria) this;
        }

        public Criteria andRowVersionIsNull() {
            addCriterion("row_version is null");
            return (Criteria) this;
        }

        public Criteria andRowVersionIsNotNull() {
            addCriterion("row_version is not null");
            return (Criteria) this;
        }

        public Criteria andRowVersionEqualTo(Integer value) {
            addCriterion("row_version =", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionNotEqualTo(Integer value) {
            addCriterion("row_version <>", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionGreaterThan(Integer value) {
            addCriterion("row_version >", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("row_version >=", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionLessThan(Integer value) {
            addCriterion("row_version <", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionLessThanOrEqualTo(Integer value) {
            addCriterion("row_version <=", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionIn(List<Integer> values) {
            addCriterion("row_version in", values, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionNotIn(List<Integer> values) {
            addCriterion("row_version not in", values, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionBetween(Integer value1, Integer value2) {
            addCriterion("row_version between", value1, value2, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("row_version not between", value1, value2, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(Boolean value) {
            addCriterion("is_deleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(Boolean value) {
            addCriterion("is_deleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(Boolean value) {
            addCriterion("is_deleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_deleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(Boolean value) {
            addCriterion("is_deleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("is_deleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<Boolean> values) {
            addCriterion("is_deleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<Boolean> values) {
            addCriterion("is_deleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("is_deleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_deleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table walker_transaction
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table walker_transaction
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}