package walker.application.notify.entity;

public class WalkerTransaction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column walker_transaction.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column walker_transaction.gmt_create
     *
     * @mbggenerated
     */
    private Long gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column walker_transaction.gmt_modified
     *
     * @mbggenerated
     */
    private Long gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column walker_transaction.app_id
     *
     * @mbggenerated
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column walker_transaction.master_gid
     *
     * @mbggenerated
     */
    private String masterGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column walker_transaction.branch_gid
     *
     * @mbggenerated
     */
    private String branchGid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column walker_transaction.is_declare
     *
     * @mbggenerated
     */
    private Boolean isDeclare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column walker_transaction.tx_status
     *
     * @mbggenerated
     */
    private Integer txStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column walker_transaction.row_version
     *
     * @mbggenerated
     */
    private Integer rowVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column walker_transaction.is_deleted
     *
     * @mbggenerated
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column walker_transaction.id
     *
     * @return the value of walker_transaction.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column walker_transaction.id
     *
     * @param id the value for walker_transaction.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column walker_transaction.gmt_create
     *
     * @return the value of walker_transaction.gmt_create
     *
     * @mbggenerated
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column walker_transaction.gmt_create
     *
     * @param gmtCreate the value for walker_transaction.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column walker_transaction.gmt_modified
     *
     * @return the value of walker_transaction.gmt_modified
     *
     * @mbggenerated
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column walker_transaction.gmt_modified
     *
     * @param gmtModified the value for walker_transaction.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column walker_transaction.app_id
     *
     * @return the value of walker_transaction.app_id
     *
     * @mbggenerated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column walker_transaction.app_id
     *
     * @param appId the value for walker_transaction.app_id
     *
     * @mbggenerated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column walker_transaction.master_gid
     *
     * @return the value of walker_transaction.master_gid
     *
     * @mbggenerated
     */
    public String getMasterGid() {
        return masterGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column walker_transaction.master_gid
     *
     * @param masterGid the value for walker_transaction.master_gid
     *
     * @mbggenerated
     */
    public void setMasterGid(String masterGid) {
        this.masterGid = masterGid == null ? null : masterGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column walker_transaction.branch_gid
     *
     * @return the value of walker_transaction.branch_gid
     *
     * @mbggenerated
     */
    public String getBranchGid() {
        return branchGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column walker_transaction.branch_gid
     *
     * @param branchGid the value for walker_transaction.branch_gid
     *
     * @mbggenerated
     */
    public void setBranchGid(String branchGid) {
        this.branchGid = branchGid == null ? null : branchGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column walker_transaction.is_declare
     *
     * @return the value of walker_transaction.is_declare
     *
     * @mbggenerated
     */
    public Boolean getIsDeclare() {
        return isDeclare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column walker_transaction.is_declare
     *
     * @param isDeclare the value for walker_transaction.is_declare
     *
     * @mbggenerated
     */
    public void setIsDeclare(Boolean isDeclare) {
        this.isDeclare = isDeclare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column walker_transaction.tx_status
     *
     * @return the value of walker_transaction.tx_status
     *
     * @mbggenerated
     */
    public Integer getTxStatus() {
        return txStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column walker_transaction.tx_status
     *
     * @param txStatus the value for walker_transaction.tx_status
     *
     * @mbggenerated
     */
    public void setTxStatus(Integer txStatus) {
        this.txStatus = txStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column walker_transaction.row_version
     *
     * @return the value of walker_transaction.row_version
     *
     * @mbggenerated
     */
    public Integer getRowVersion() {
        return rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column walker_transaction.row_version
     *
     * @param rowVersion the value for walker_transaction.row_version
     *
     * @mbggenerated
     */
    public void setRowVersion(Integer rowVersion) {
        this.rowVersion = rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column walker_transaction.is_deleted
     *
     * @return the value of walker_transaction.is_deleted
     *
     * @mbggenerated
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column walker_transaction.is_deleted
     *
     * @param isDeleted the value for walker_transaction.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}